implements Windows on Github Actions

diff --git a/.github/workflows/knuth.yml b/.github/workflows/knuth.yml
--- a/.github/workflows/knuth.yml
+++ b/.github/workflows/knuth.yml
@@ -16,9 +16,10 @@ jobs:
       - name: Generate Job Matrix
         id: set-matrix
         env:
-          MATRIX: '{"config": [{"name": "NodeJS 14","nodejs_version": "14","os": "ubuntu-20.04"},
-                               {"name": "NodeJS 12","nodejs_version": "12","os": "ubuntu-20.04"},
-                               {"name": "NodeJS 10","nodejs_version": "10","os": "ubuntu-20.04"},
+          MATRIX: '{"config": [{"name": "Linux NodeJS 14","nodejs_version": "14","os": "ubuntu-20.04","os_kind": "linux"},
+                               {"name": "Linux NodeJS 12","nodejs_version": "12","os": "ubuntu-20.04","os_kind": "linux"},
+                               {"name": "macOS NodeJS 12","nodejs_version": "14","os": "macos-10.15","os_kind": "macos"},
+                               {"name": "Windows NodeJS 14","nodejs_version": "14","os": "windows-2019","os_kind": "windows"},
                                ]}'
         run: |
           # MATRIX=$(cat ./ci_utils/.github/matrix.json)
@@ -59,94 +60,95 @@ jobs:
       #     conan user
       #   shell: cmd
 
-      - name: Settting EnvVars (Linux)
-        # if: ${{ matrix.config.compiler == 'GCC' }}
+      - name: Settting EnvVars (Unix)
+        if: ${{ matrix.config.os_kind != 'windows' }}
         shell: bash
         run: |
-          # echo "CONAN_GCC_VERSIONS=${{ matrix.config.version }}" >> $GITHUB_ENV
-          # echo "CONAN_DOCKER_IMAGE=conanio/gcc${{ matrix.config.version }}" >> $GITHUB_ENV
           echo "NODEJS_VERSION=${{ matrix.config.nodejs_version }}" >> $GITHUB_ENV
 
+      - name: Settting EnvVars (Windows)
+        if: ${{ matrix.config.os_kind == 'windows' }}
+        shell: powershell
+        run: |
+          echo "NODEJS_VERSION=${{ matrix.config.nodejs_version }}" >> $Env:GITHUB_ENV
 
-      # - name: Settting EnvVars (macOS)
-      #   if: ${{ matrix.config.compiler == 'apple-clang' }}
-      #   shell: bash
-      #   run: |
-      #     echo "CONAN_APPLE_CLANG_VERSIONS=${{ matrix.config.version }}.0" >> $GITHUB_ENV
-
-      # - name: Settting EnvVars (Windows)
-      #   if: ${{ matrix.config.compiler == 'Visual Studio' }}
-      #   # shell: bash
-      #   shell: powershell
-      #   run: |
-      #     echo "CONAN_VISUAL_VERSIONS=${{ matrix.config.version }}" >> $Env:GITHUB_ENV
-      #     echo "CONAN_VISUAL_RUNTIMES=${{ matrix.config.msvc_runtime }}" >> $Env:GITHUB_ENV
-      #     # echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $env:GITHUB_ENV
-
-      - name: Build (Unix)
-        # if: ${{ matrix.config.compiler != 'Visual Studio' }}
+      - name: Build (Linux)
+        if: ${{ matrix.config.os_kind == 'linux' }}
         env:
           NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
           NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
         shell: bash
         run: |
-          # echo ${{ matrix.config.compiler }}
-          # echo ${BPT_MATRIX}
-
-          echo ${PWD}
-          pwd
-
-          echo ${NPM_AUTH_TOKEN}
-          echo ${NPM_EMAIL}
-          echo ${NODEJS_VERSION}
-          echo ${NODE_PRE_GYP_GITHUB_TOKEN}
-          
-          # export KTH_BRANCH=$(echo '${{ github.ref }}' | awk -F '/' '{print $3}')
-          # echo "My branch name is $KTH_BRANCH"
-        
+          # echo ${NPM_AUTH_TOKEN}
+          # echo ${NPM_EMAIL}
+          # echo ${NODEJS_VERSION}
+          # echo ${NODE_PRE_GYP_GITHUB_TOKEN}
+                  
           chmod a+x .travis/entrypoint.sh
           /usr/bin/docker run -u root --rm -e NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN -e NPM_EMAIL=$NPM_EMAIL -e NODEJS_VERSION=$NODEJS_VERSION -e NODE_PRE_GYP_GITHUB_TOKEN=$NODE_PRE_GYP_GITHUB_TOKEN -v ${PWD}:/home/conan/project -v ${PWD}/.travis/entrypoint.sh:/tmp/entrypoint.sh conanio/gcc10 /bin/bash -c /tmp/entrypoint.sh
 
+      - name: Build (Windows)
+        if: ${{ matrix.config.os_kind == 'windows' }}
+        env:
+          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
+          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
+        shell: powershell
+        run: |
+          # Write-Host "CONAN_VISUAL_VERSIONS: $Env:CONAN_VISUAL_VERSIONS"
+          # Write-Host "CONAN_VISUAL_RUNTIMES: $Env:CONAN_VISUAL_RUNTIMES"
+
+          Install-Product node $env:nodejs_version x64
+          npm --version
+          npm -g install npm@next
+          npm --version
+          npm install -g node-gyp
+          npm install -g node-pre-gyp
+          npm install -g aws-sdk
+          npm install -g node-pre-gyp-github
+
+          pip --version
+          pip install kthbuild --upgrade
+          python --version
+          conan user # It creates the conan data directory
+
+          node --version
+          npm --version
+          python --version
+          # cl /version
+
+          Write-Host "FerFerFer"
+          node -p "process.arch"
+          Write-Host "FerFerFer"
+
+          conan user
+          conan remote add kth_temp https://api.bintray.com/conan/k-nuth/kth
+          # conan install .
+
+          npm install
+          node-pre-gyp configure build package
+          # node-pre-gyp configure --verbose
+          # node-pre-gyp build --verbose
+          # node-pre-gyp package --verbose
+          node-pre-gyp-github publish --release  || true
 
 
-      # - name: Build (Windows)
-      #   if: ${{ matrix.config.compiler == 'Visual Studio' }}
-      #   env:
-      #     CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
-      #     CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
-      #     CONAN_STABLE_BRANCH_PATTERN: "master$" #"release/*"
-      #   shell: powershell
-      #   run: |
-      #     # echo ${{ matrix.config.compiler }}
-      #     # echo %BPT_MATRIX%
-      #     # echo %CONAN_STABLE_BRANCH_PATTERN%
-      #     # echo %CONAN_LOGIN_USERNAME%
 
-      #     Write-Host "CONAN_VISUAL_VERSIONS: $Env:CONAN_VISUAL_VERSIONS"
-      #     Write-Host "CONAN_VISUAL_RUNTIMES: $Env:CONAN_VISUAL_RUNTIMES"
 
-      #     $Env:KTH_BRANCH = "${{ github.ref }}".Split("/")[2]
-      #     Write-Host "My branch name is $Env:KTH_BRANCH"
+          # $ErrorActionPreference = 'SilentlyContinue'
+          # conan remote add kth https://api.bintray.com/conan/k-nuth/kth
+          # $ErrorActionPreference = 'Continue'
 
-      #     $a = python ci_utils/set_envvars_and_files.py
-      #     Write-Host $a
-      #     Invoke-Expression $a
+          # # conan info . --only None
+          # # conan info . --only None -s compiler=gcc -s compiler.version=5 -s compiler.libcxx=libstdc++
+          # python ci_utils/process_conan_reqs.py
 
-      #     $ErrorActionPreference = 'SilentlyContinue'
-      #     conan remote add kth https://api.bintray.com/conan/k-nuth/kth
-      #     $ErrorActionPreference = 'Continue'
+          # $ErrorActionPreference = 'SilentlyContinue'
+          # conan remove "*" -f
+          # conan remote remove kth
+          # conan remote remove kthbuild_kth_temp_
+          # $ErrorActionPreference = 'Continue'
 
-      #     # conan info . --only None
-      #     # conan info . --only None -s compiler=gcc -s compiler.version=5 -s compiler.libcxx=libstdc++
-      #     python ci_utils/process_conan_reqs.py
-
-      #     $ErrorActionPreference = 'SilentlyContinue'
-      #     conan remove "*" -f
-      #     conan remote remove kth
-      #     conan remote remove kthbuild_kth_temp_
-      #     $ErrorActionPreference = 'Continue'
-
-      #     python build.py
+          # python build.py
 
 
 
